# config/meta.yml

meta_product_name: "Hoxton Digital"
meta_title: "Londo Web Development Agency"
meta_description: "We are a uniquely structured software factory based in London with presence in over 6 countries."
meta_image: "meta-image.png"                       # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
